#include "../Public/BaseObject.h"

using namespace Lumen::Core;

BaseObject::BaseObject()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Core::BaseObject>("BaseObject")
		.constructor<>()
		.method("Serialize", &BaseObject::Serialize)
	;
}