// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<typename T>
struct Ubpa::USRefl::TypeInfo<Lumen::Refl::Vec<T>> :
    TypeInfoBase<Lumen::Refl::Vec<T>>
{
    static constexpr AttrList attrs = {
        Attr {TSTR("size"), sizeof(T)},
    };
    static constexpr FieldList fields = {
        Field {TSTR(UMeta::constructor), WrapConstructor<Lumen::Refl::Vec<T>()>()},
        Field {TSTR(UMeta::constructor), WrapConstructor<Lumen::Refl::Vec<T>(T, T)>()},
        Field {TSTR(UMeta::destructor), WrapDestructor<Lumen::Refl::Vec<T>>()},
        Field {TSTR("x"), &Lumen::Refl::Vec<T>::x, AttrList {
            Attr {TSTR("not_serialize")},
        }},
        Field {TSTR("y"), &Lumen::Refl::Vec<T>::y, AttrList {
            Attr {TSTR("info"), "hello"},
            Attr {TSTR("maximum"), 10.f},
        }},
        Field {TSTR("num"), &Lumen::Refl::Vec<T>::num},
        Field {TSTR("Sum"), static_cast<float(Lumen::Refl::Vec<T>::*)()const>(&Lumen::Refl::Vec<T>::Sum)},
        Field {TSTR("Sum"), static_cast<float(Lumen::Refl::Vec<T>::*)(float, float)const>(&Lumen::Refl::Vec<T>::Sum), AttrList {
            Attr {TSTR(UMeta::default_functions), std::tuple {
                [](Lumen::Refl::Vec<T> const* this_, float z){ return this_->Sum(std::forward<float>(z)); }
            }},
        }},
        Field {TSTR("Dot"), &Lumen::Refl::Vec<T>::Dot},
    };
};

