#include "../Public/AssetRef.h"

AssetRef::AssetRef()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<AssetRef>("AssetRef")
		.constructor<>()
		.property("name", &AssetRef::name)
		(
			metadata("serialize", true)
		)
		.property("guid", &AssetRef::guid)
		(
			metadata("serialize", true)
		)
	;
}