#include "../Public/BaseObject.h"

// This following is generated by Ubpa::USRefl::AutoRefl

using namespace Lumen::Game;

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::BaseObject>("BaseObject")
		.method("Test", &BaseObject::Test)
	;
}