#include "../Public/Component.h"

// This following is generated by Ubpa::USRefl::AutoRefl

using namespace Lumen::Game;

void AssetRef::Serialize(Archive& ar)
{
	ar.BeginObject();
	ar << "guid" << guid.str();
	ar.EndObject();
}


Component::Component()
{

}

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::AssetRef>("AssetRef")
		.property("guid", &AssetRef::guid)
		.property("ref", &AssetRef::ref)
		.method("Serialize", &AssetRef::Serialize)
		.constructor<>()
	;
	registration::class_<Lumen::Game::Component>("Component")
		.constructor<>()
		.method("GetName", &Component::GetName)
		.method("SetName", &Component::SetName)
		.property("mName", &Component::mName, registration::private_access)
		(
			metadata("serialize", true)
		)
	;
}