#include "../Public/Component.h"

using namespace Lumen::Game;

Component::Component()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::AssetRef>("AssetRef")
		.property("name", &AssetRef::name)
		(
			metadata("serialize", true)
		)
		.property("guid", &AssetRef::guid)
		(
			metadata("serialize", true)
		)
		.constructor<>()
	;
	registration::class_<Lumen::Game::Component>("Component")
		.constructor<>()
	;
}