#include "../Public/Component.h"

using namespace Lumen::Game;

Component::Component()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Component>("Component")
		.constructor<>()
	;
}