#include "../Public/Entity.h"

using namespace Lumen::Game;

Entity::Entity()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Entity>("Entity")
		.constructor<>()
		.method("BeginPlay", &Entity::BeginPlay)
		.method("Tick", &Entity::Tick)
		.method("GetName", &Entity::GetName)
		.method("SetName", &Entity::SetName)
		.method("GetTransform", &Entity::GetTransform)
		.method("GetTransformPtr", &Entity::GetTransformPtr)
		.method("GetMeshContainer", &Entity::GetMeshContainer)
		.method("GetMeshContainerPtr", &Entity::GetMeshContainerPtr)
		.method("SetMeshGUID", &Entity::SetMeshGUID)
		.method("GetMeshRenderer", &Entity::GetMeshRenderer)
		.method("SetShaderGUID", &Entity::SetShaderGUID)
		.property("mName", &Entity::mName, registration::protected_access)
		(
			metadata("serialize", true)
		)
		.property("mTransform", &Entity::mTransform, registration::protected_access)
		(
			metadata("serialize", true)
		)
		.property("mMeshContainer", &Entity::mMeshContainer, registration::protected_access)
		(
			metadata("serialize", true)
		)
		.property("mMeshRenderer", &Entity::mMeshRenderer, registration::protected_access)
		(
			metadata("serialize", true)
		)
	;
}