#include "../Public/Entity.h"

// This following is generated by Ubpa::USRefl::AutoRefl

using namespace Lumen::Game;

Entity::Entity()
{

}

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Entity>("Entity")
		.constructor<>()
		.method("GetName", &Entity::GetName)
		.method("SetName", &Entity::SetName)
		.property("mName", &Entity::mName, registration::private_access)
		(
			metadata("serialize", true)
		)
		.property("mComponents", &Entity::mComponents, registration::private_access)
		(
			metadata("serialize", true)
		)
		.property("mChildEntities", &Entity::mChildEntities, registration::private_access)
		(
			metadata("serialize", true)
		)
	;
}