#include "../Public/Entity.h"

using namespace Lumen::Game;

Entity::Entity()
{
	mClassName = "Entity";
	mGuid = xg::newGuid();
}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Entity>("Entity")
		.constructor<>()
		.method("BeginPlay", &Entity::BeginPlay)
		.method("Tick", &Entity::Tick)
		.method("GetMeshContainer", &Entity::GetMeshContainer)
		.method("GetMeshRenderer", &Entity::GetMeshRenderer)
		.method("GetName", &Entity::GetName)
		.method("SetName", &Entity::SetName)
		.method("GetTransform", &Entity::GetTransform)
		.method("GetGuid", &Entity::GetGuid)
		.property("mClassName", &Entity::mClassName, registration::protected_access)
		(
			metadata("serialize", true)
		)
		.property("mName", &Entity::mName, registration::protected_access)
		(
			metadata("serialize", true)
		)
		.property("mTransform", &Entity::mTransform, registration::protected_access)
		(
			metadata("serialize", true)
		)
		.property("mGuid", &Entity::mGuid, registration::protected_access)
	;
}