#include "../Public/MeshRendererComponent.h"

using namespace Lumen::Game;

MeshRendererComponent::MeshRendererComponent()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::MeshRendererComponent>("MeshRendererComponent")
		.constructor<>()
		.property("shaderlabRef", &MeshRendererComponent::shaderlabRef)
		(
			metadata("serialize", true)
		)
		.property("material", &MeshRendererComponent::material)
		(
			metadata("serialize", true)
		)
	;
}