#include "../Public/MeshEntity.h"

using namespace Lumen::Game;

MeshEntity::MeshEntity()
{
	mClassName = "MeshEntity";
}

MeshComponent* MeshEntity::GetMeshContainer() const
{
	MeshComponent* ptr = (MeshComponent*)&mMeshContainer;
	return ptr;
}

MeshRendererComponent* MeshEntity::GetMeshRenderer() const
{
	MeshRendererComponent* ptr = (MeshRendererComponent*)&mMeshRenderer;
	return ptr;
}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::MeshEntity>("MeshEntity")
		.constructor<>()
		.method("BeginPlay", &MeshEntity::BeginPlay)
		.method("Tick", &MeshEntity::Tick)
		.method("GetMeshContainer", &MeshEntity::GetMeshContainer)
		.method("GetMeshRenderer", &MeshEntity::GetMeshRenderer)
		.method("SetMeshGUID", &MeshEntity::SetMeshGUID)
		.property("mMeshContainer", &MeshEntity::mMeshContainer, registration::protected_access)
		(
			metadata("serialize", true)
		)
		.property("mMeshRenderer", &MeshEntity::mMeshRenderer, registration::protected_access)
		(
			metadata("serialize", true)
		)
	;
}