#include "../Public/MeshRendererComponent.h"

// This following is generated by Ubpa::USRefl::AutoRefl

using namespace Lumen::Game;

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::MeshRendererComponent>("MeshRendererComponent")
		.constructor<>()
		.property("materialRef", &MeshRendererComponent::materialRef)
		(
			metadata("serialize", true)
		)
	;
}