#include "../Public/TransformComponent.h"

// This following is generated by Ubpa::USRefl::AutoRefl

using namespace Lumen::Game;

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::TransformComponent>("TransformComponent")
		.constructor<>()
		.property("position", &TransformComponent::position)
		(
			metadata("serialize", true)
		)
		.property("rotation", &TransformComponent::rotation)
		(
			metadata("serialize", true)
		)
		.property("scale", &TransformComponent::scale)
		(
			metadata("serialize", true)
		)
	;
}