#include "Game/Asset/Public/Material.h"

using namespace Lumen::Game;

Material::Material()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Material>("Material")
		.constructor<>()
		.property("name", &Material::name)
		.property("diffuseTextureGuid", &Material::diffuseTextureGuid)
		(
			metadata("serialize", true)
		)
	;
}