#include "../Public/Meta.h"

// This following is generated by Ubpa::USRefl::AutoRefl

using namespace Lumen::Game;

Meta::Meta()
{

}

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Meta>("Meta")
		.property("guid", &Meta::guid)
		(
			metadata("serialize", true)
		)
		.constructor<>()
	;
}