#include "Game/Asset/Public/Scene.h"
#include "Render/RenderCore/Public/RenderCommand.h"

using namespace Lumen::Game;
using namespace Lumen::Render;

Scene::Scene()
{

}

Entity* Scene::CreateEntity(std::string_view className)
{
	rttr::type derivedType = rttr::type::get_by_name(className.data());
	if (!derivedType.is_valid()) return nullptr;

	// Note variant manage data life itself, we need to persistent data with shared_ptr
	variant derived = derivedType.create();
	auto entity = derived.get_value<std::shared_ptr<Entity>>();
	entity->SetName(className.data() + std::string("_") + std::to_string(nameIndex++));
	entities.emplace_back(entity);

	if (entity->GetMeshContainer())
		ENQUEUE_RENDER_COMMAND("CreateEntity", [entity](RHIContext* graphicsContext) {
			const Entity entityProxy(*entity.get());
			const MeshComponent meshContainer(*entity->GetMeshContainer());
			const MeshRendererComponent meshRenderer(*entity->GetMeshRenderer());
			graphicsContext->CreateEntity(entityProxy, meshContainer, meshRenderer);
		});

	return entities.back().get();
}

void Scene::DeleteEntity(std::string_view name)
{
	for (int i = 0; i < entities.size(); i++)
	{
		if (entities[i]->GetName() == name.data())
		{
			auto guid = entities[i]->GetGuid().str();
			ENQUEUE_RENDER_COMMAND("RemoveRenderItem", [guid](RHIContext* graphicsContext) {
				graphicsContext->RemoveRenderItem(guid);
			});

			entities.erase(entities.begin() + i);
			break;
		}
	}
}

void Scene::UpdateEntity(Entity* entity)
{
	if (entity->GetMeshContainer() && entity->GetMeshRenderer())
		ENQUEUE_RENDER_COMMAND("UpdateEntity", [entity](RHIContext* graphicsContext) {
			const Entity entityProxy(*entity);
			const MeshComponent meshContainer(*entity->GetMeshContainer());
			const MeshRendererComponent meshRenderer(*entity->GetMeshRenderer());
			graphicsContext->UpdateEntity(entityProxy, meshContainer, meshRenderer);
		});
}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Scene>("Scene")
		.constructor<>()
		.method("CreateEntity", &Scene::CreateEntity)
		.method("DeleteEntity", &Scene::DeleteEntity)
		.method("UpdateEntity", &Scene::UpdateEntity)
		.property("entities", &Scene::entities)
		(
			metadata("serialize", true)
		)
		.property("nameIndex", &Scene::nameIndex)
	;
}