#include "../Public/Scene.h"

using namespace Lumen::Game;

Scene::Scene()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Scene>("Scene")
		.constructor<>()
		.property("camera", &Scene::camera)
		(
			metadata("serialize", true)
		)
		.property("light", &Scene::light)
		(
			metadata("serialize", true)
		)
		.property("entities", &Scene::entities)
		(
			metadata("serialize", true)
		)
	;
}