#include "../Public/Scene.h"

using namespace Lumen::Game;

Scene::Scene()
{

}

Scene::Scene(const Scene& rhs)
{
	entities = rhs.entities;
}

Scene::Scene(Scene&& rhs)
{
	entities = std::move(rhs.entities);
}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<Lumen::Game::Scene>("Scene")
		.constructor<>()
		.constructor<const Scene&>()
		.constructor<Scene&&>()
		.property("camera", &Scene::camera)
		(
			metadata("serialize", true)
		)
		.property("light", &Scene::light)
		(
			metadata("serialize", true)
		)
		.property("entities", &Scene::entities)
		(
			metadata("serialize", true)
		)
	;
}