#include "../Public/TestEntity.h"

TestEntity::TestEntity()
{
	mClassName = "TestEntity";
}

void TestEntity::BeginPlay()
{

}

void TestEntity::Tick()
{
	mTransform.position.x += 0.1f;
}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<TestEntity>("TestEntity")
		.constructor<>()
		.method("BeginPlay", &TestEntity::BeginPlay)
		.method("Tick", &TestEntity::Tick)
		.property("mIntValue", &TestEntity::mIntValue, registration::private_access)
		(
			metadata("serialize", true)
		)
		.property("mStrValue", &TestEntity::mStrValue, registration::private_access)
		(
			metadata("serialize", true)
		)
	;
}