#include "../Public/TestEntity.h"

TestEntity::TestEntity()
{

}

void TestEntity::BeginPlay()
{

}

void TestEntity::Tick()
{

}

// This following is generated by Ubpa::USRefl::AutoRefl

RTTR_REGISTRATION
{
	registration::class_<TestEntity>("TestEntity")
		.constructor<>()
		.property("mIntValue", &TestEntity::mIntValue, registration::private_access)
		(
			metadata("serialize", true)
		)
	;
}